spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jadmin?characterEncoding=utf8
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        #解决springdatajpa 在解析实体类的Cloumn的时候驼峰自动转为下划线
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  #在原来静态内部资源的基础上，添加外部资源
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${jadmin.fileBasePath}
    
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  port: 8080
  servlet:
    jsp:
      init-parameters:
        #设置jsp实时生效
        development: true
  
#项目其他配置可放到jadmin标签下
jadmin:

  #上传文件存放的路径
  fileBasePath: D://jcsa/jadmin

  #是否开启调试模式
  debug: true
    
  #该属性为后台页面 的显示顺序，写在前面，就显示在前面
  adminPage: #List
    - 角色管理
    - 用户管理
    - 系统设置
    - 数据字典
    - 系统日志
    
  #该属性为后台页面，页面按钮的显示顺序，写在前面，就显示在前面
  adminButton: #List
    - 添加
    - 详情
    - 编辑
    - 删除
    
  #如果需要通过配置文件指定 启动哪些调度，可在此处配置，注意需开启WebApplication类的@EnableQuartz注解，并将ymlConfig设置为true
  #格式为包名.类名，如果在com.jadmin.quartz包下，可只写类名（注意大小写）
  taskList: #List